spring:
  application:
    name: MongoJdbc
  data:
    mongodb:
      uri: mongodb://localhost:27017/mongospring
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/helha